### ISSUE TITLE
Vague error with `maybe rm ./*`

### ISSUE THREAD

**Issue by Qix-** [p-e-w/maybe#12]
Getting a vague error upon `maybe rm ./*`:

```console
Warning: Running without traceFork support. Syscalls from subprocesses can not be intercepted.
Traceback (most recent call last):
  File "/usr/local/bin/maybe", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/maybe/maybe.py", line 154, in main
    prepareProcess(process)
  File "/usr/local/lib/python2.7/site-packages/maybe/maybe.py", line 53, in prepareProcess
    process.syscall()
  File "/usr/local/lib/python2.7/site-packages/ptrace/debugger/process.py", line 469, in syscall
    ptrace_syscall(self.pid, signum)
  File "/usr/local/lib/python2.7/site-packages/ptrace/binding/func.py", line 254, in ptrace_syscall
    ptrace(PTRACE_SYSCALL, pid, 1, signum)
  File "/usr/local/lib/python2.7/site-packages/ptrace/binding/func.py", line 148, in ptrace
    raise PtraceError(message, errno=errno, pid=pid)
ptrace.error.PtraceError: ptrace(cmd=22, pid=35717, 1, 0) error #22: Invalid argument
```

Installed using `sudo pip install maybe`. On OS X El Capitan.

**Comment by jarek** [comment]
This is not path specific but rather due to OS X not being supported in general, see https://github.com/p-e-w/maybe/issues/3

**Comment by Qix-** [comment]
Aha! Thanks :)
