### ISSUE TITLE
terminfo database problem

### ISSUE THREAD

**Issue by janpipek** [p-e-w/maybe#24]
Hi, your project sounds quite interesting. So I pip-ed it and tried with the simplest command possible:

```
maybe rm filename
```

However, what I received, was an error message:

```
Traceback (most recent call last):
  File "/home/username/anaconda3/bin/maybe", line 7, in <module>
    from maybe.maybe import main
  File "/home/username/anaconda3/lib/python3.4/site-packages/maybe/maybe.py", line 23, in <module>
    from .syscall_filters import SYSCALL_FILTERS
  File "/home/username/anaconda3/lib/python3.4/site-packages/maybe/syscall_filters.py", line 17, in <module>
    from .utilities import T, format_permissions
  File "/home/username/anaconda3/lib/python3.4/site-packages/maybe/utilities.py", line 16, in <module>
    T = Terminal()
  File "/home/username/anaconda3/lib/python3.4/site-packages/blessings/__init__.py", line 106, in __init__
    self._init_descriptor)
_curses.error: setupterm: could not find terminfo database
```

Do you know what could be source of the problem?
Thanks,
Jan

P.S. Anaconda distribution, Python 3.4.3, Linux (Fedora 22)

**Comment by p-e-w** [comment]
A quick web search shows this to be a common issue, and the "fix" apparently consists of setting your `TERM` environment variable to `xterm-256color`.

I use Fedora myself so the root cause is likely Anaconda or your terminal. Perhaps Anaconda clears the `TERM` variable for some reason? Many terminal emulators (including GNOME Terminal, but *not* Guake) set `xterm-256color` already, so this should not be necessary unless something overwrites the terminal default.

**Comment by janpipek** [comment]
Thanks.

Strangely enough, I upgraded Anaconda to Python 3.5 in the meantime (for other reasons) and the problem disappeared. I have (and probably did have) the TERM set correctly. So the distribution's fault?

Anyway, it works. So as far I am concerned, you can close the issue :-)
