### ISSUE TITLE
Seems *maybe* don't support OSX 10.12

### ISSUE THREAD

**Issue by lx865712528** [p-e-w/maybe#37]
When I run _maybe_ in OSX 10.12, I always receive errors below:

``` Python
Warning: Running without traceFork support. Syscalls from subprocesses can not be intercepted.
Traceback (most recent call last):
  File "/usr/local/bin/maybe", line 9, in <module>
    load_entry_point('maybe==0.4.0', 'console_scripts', 'maybe')()
  File "/Library/Python/2.7/site-packages/maybe/maybe.py", line 159, in main
    prepareProcess(process)
  File "/Library/Python/2.7/site-packages/maybe/maybe.py", line 58, in prepareProcess
    process.syscall()
  File "/Library/Python/2.7/site-packages/ptrace/debugger/process.py", line 469, in syscall
    ptrace_syscall(self.pid, signum)
  File "/Library/Python/2.7/site-packages/ptrace/binding/func.py", line 254, in ptrace_syscall
    ptrace(PTRACE_SYSCALL, pid, 1, signum)
  File "/Library/Python/2.7/site-packages/ptrace/binding/func.py", line 148, in ptrace
    raise PtraceError(message, errno=errno, pid=pid)
ptrace.error.PtraceError: ptrace(cmd=22, pid=88532, 1, 0) error #22: Invalid argument
```

**Comment by herrbischoff** [comment]
Yup, same here. Uninstalling and moving on.

**Comment by alphapapa** [comment]
Well, it doesn't claim to support anything but Linux.  Maybe give it time or contribute a patch?

**Comment by p-e-w** [comment]
As documented in the README, `maybe` is Linux-only.

**Comment by herrbischoff** [comment]
You're correct, but only since https://github.com/p-e-w/maybe/commit/c33903537d68e006a6fc65f219bdb42dbea320b2. Which, to be quite fair, is indeed before this issue was created.
