### ISSUE TITLE
Issue with CMDer on W10

### ISSUE THREAD

**Issue by diblaze** [p-e-w/maybe#8]
Get this when I try to use any command with "maybe".

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\maybe-script.py", line 9, in <module>
    load_entry_point('maybe==0.3.0', 'console_scripts', 'maybe')()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2355, in load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python27\lib\site-packages\maybe\maybe.py", line 15, in <module>
    from ptrace.debugger import ProcessSignal, NewProcessEvent, ProcessExecution, ProcessExit
  File "c:\python27\lib\site-packages\ptrace\debugger\__init__.py", line 6, in <module>
    from ptrace.debugger.child import ChildError
  File "c:\python27\lib\site-packages\ptrace\debugger\child.py", line 4, in <module>
    from os import (
ImportError: cannot import name fork
```

**Comment by PhilipTrauner** [comment]
### Operating system support

| OS | Support status |
| --- | --- |
| Linux | :white_check_mark: Full support |
| FreeBSD / OpenBSD | :ballot_box_with_check: Limited support (subprocesses can not be intercepted) |
| OS X | :question: Might be supported in future pending OS X support in python-ptrace |

**Comment by strelec** [comment]
Maybe (no pun intended) detect Windows and tell the user it is not supported.

**Comment by diblaze** [comment]
It was my bad, did not see the support tab...
